### PR TITLE
Ui redesign

### PR DESCRIPTION
**Pull request by TessyPowder**
With this PR I want to change the design of Flowupoad to more look like the rest of nextcloud.
This is work in progress !

### CODE REVIEW

**Comment by e-alfred** [comment]
Thanks for your help! Do you have some screenshot/mock-up on how it should look like?

**Comment by TessyPowder** [comment]
Currently it looks like this:
image

The Buttons look like the standard buttons in Nextcloud and they now have icons.
The Table looks like the File Browser in the Files App.
Hovered Upload Rows have a gray background (like in the Files app)
The Progressbar background is now a bit darker than before.
The Buttons to pause, resume, cancel and retry are now an Icon and not a button.
The blue labels now have the color of the nextcloud navbar (before it was the bootstrap blue) and they are located below the Buttons.

**Comment by TessyPowder** [comment]
TODO:

- I changed the button text from "Upload/Resume all" to "Start/Resume". That needs to get translated and the l10n files have to be changed
- Remove Bootstrap completely (?). It is only being used at the blue labels and this can easily done without bootstrap
- testing Nextcloud 17 (currently only tested on Nextcloud 16) (and older Versions ?)
- Mobile optimisations (? - Probably nobody uses Flowupload on their phone but it could be useful)

**Comment by TessyPowder** [comment]
> All translations are done through Transiflex and their awesome community and the Nextcloud Bot keeps track of all translatable strings as long as they are inside t() tags so there is no need to change all localisation files manually

I know but i dont have any permissions to change Transifex configurations. (I changed the files for testing / merging a working version)

**Comment by TessyPowder** [comment]
# New GIF Image for README.md

file

This is what I got so far:
Its a Full HD and 15 FPS Gif, that is 6 MB big.
(done with OBS Studio, kdenlive, ffmpeg (downscaling and framerate change) and gifski - any better way to do this ?)
Is 6 MB ok for embedding in the README ?

**Comment by TessyPowder** [comment]
I made more Versions of the Screenshot:
## Light Mode
### 4k Video (527 KB)
https://nextcloud.fractava.com/index.php/s/flowupload-screenshot-light

### 960x488 15fps (2.4 MB)
low resolution 15fps

### 960x488 10fps (1.6 MB)
low resolution 10fps


### 1920x976 15fps (6.1 MB)
high resolution 15fps

### 1920x976 10fps (4.1 MB)
high resolution 10fps

## Dark Mode (via Nextcloud Acessibility)
### 4k Video (599 KB)
https://nextcloud.fractava.com/index.php/s/flowupload-screenshot-dark

### 960x488 15fps (2.7 MB)
low resolution 15fps

### 960x488 10fps (1.7 MB)
low resolution 10fps

### 1920x976 15fps (6.8 MB)
high resolution 15fps

### 1920x976 10fps(4.6 MB)
high resolution 10fps

I think for the Readme.md 960x488 10fps (1.6 MB) should be enough.

**Comment by TessyPowder** [comment]
This is how the UI looks now:

## Mobile:
image


## Desktop: (didnt change)
image

On Desktop the width of the columns is still defined in percent, but on mobile the browser determines the needed width.
On mobile buttons stack on top of each other and not besides.
On mobile the id column , the bytes uploaded so far and the progressbar get hidden.
On both mobile and desktop file names get shortened (like "foobar...") if theres not enough space available.
On mobile the user can not zoom anymore (makes it feel less like a website but more like a app).

**Comment by e-alfred** [comment]
Awesome work! You could create GIF files using Peek on Linux for example.

One use case for a mobile version of Flowupload could be a smartphone without any (Nextcloud) app installed and the user could upload files (taken with the camera for example) to their Nextcloud by logging in with a browser and uploading them.

**Comment by fractava** [comment]
> Awesome work! You could create GIF files using Peek on Linux for example.

OK. But i think gifski worked pretty well

**Comment by TessyPowder** [comment]
Nextcloud 15 testing is done

**Comment by TessyPowder** [comment]
Everything works fine on Nextcloud 17.

**Comment by TessyPowder** [comment]
I think this PR is ready to get merged

**Comment by e-alfred** [comment]
Thanks for your help! I merge this and will release a new version as soon as some translations from Transiflex roll in.

**Pull request merged**
