### PR TITLE
Fixing small stuff

### PR DESCRIPTION
**Pull request by TessyPowder**
... to make Codacy happy 😀

### CODE REVIEW

**Comment by e-alfred** [comment]
Can you bump the minimist package too?

Currently if I try to run 'npm run build' I am getting the following errors:

ERROR in ./src/App.vue
Module Error (from ./node_modules/eslint-loader/dist/cjs.js):

```
flowupload/src/App.vue
   14:2   error  Mixed spaces and tabs                                                                                                                                                          no-mixed-spaces-and-tabs
   21:6   error  This 'v-if' should be moved to the wrapper element                                                                                                                             vue/no-use-v-if-with-v-for
  125:8   error  Elements in iteration expect to have 'v-bind:key' directives                                                                                                                   vue/require-v-for-key
  125:12  error  The 'filteredFiles' variable inside 'v-for' directive should be replaced with a computed property that returns filtered array instead. You should not mix 'v-for' with 'v-if'  vue/no-use-v-if-with-v-for
  198:3   error  The "AppSidebar" component has been registered but not used                                                                                                                    vue/no-unused-components
  199:3   error  The "AppSidebarTab" component has been registered but not used                                                                                                                 vue/no-unused-components
  202:3   error  The "ActionLink" component has been registered but not used                                                                                                                    vue/no-unused-components
  203:3   error  The "AppNavigationIconBullet" component has been registered but not used                                                                                                       vue/no-unused-components
  204:3   error  The "ActionCheckbox" component has been registered but not used                                                                                                                vue/no-unused-components
  205:3   error  The "ActionInput" component has been registered but not used                                                                                                                   vue/no-unused-components
  206:3   error  The "ActionRouter" component has been registered but not used                                                                                                                  vue/no-unused-components
  207:3   error  The "ActionText" component has been registered but not used                                                                                                                    vue/no-unused-components
  208:3   error  The "ActionTextEditable" component has been registered but not used                                                                                                            vue/no-unused-components
  214:13  error  'OC' is not defined                                                                                                                                                            no-undef
  226:4   error  Unexpected console statement                                                                                                                                                   no-console
  241:4   error  '$' is not defined                                                                                                                                                             no-undef
  250:2   error  Mixed spaces and tabs                                                                                                                                                          no-mixed-spaces-and-tabs
  251:2   error  Mixed spaces and tabs                                                                                                                                                          no-mixed-spaces-and-tabs
  251:11  error  'OCA' is not defined                                                                                                                                                           no-undef
  252:1   error  Expected indentation of 4 tabs but found 16 spaces                                                                                                                             indent
  253:2   error  Mixed spaces and tabs                                                                                                                                                          no-mixed-spaces-and-tabs
  254:2   error  Mixed spaces and tabs                                                                                                                                                          no-mixed-spaces-and-tabs
  255:2   error  Mixed spaces and tabs                                                                                                                                                          no-mixed-spaces-and-tabs
  267:4   error  Unexpected console statement                                                                                                                                                   no-console
  276:41  error  'reject' is defined but never used                                                                                                                                             no-unused-vars
  277:5   error  '$' is not defined                                                                                                                                                             no-undef
  288:41  error  'reject' is defined but never used                                                                                                                                             no-unused-vars
  302:4   error  'OC' is not defined                                                                                                                                                            no-undef
  307:44  error  'OC' is not defined                                                                                                                                                            no-undef
  326:2   error  Mixed spaces and tabs                                                                                                                                                          no-mixed-spaces-and-tabs
  327:2   error  Mixed spaces and tabs                                                                                                                                                          no-mixed-spaces-and-tabs
  328:2   error  Mixed spaces and tabs                                                                                                                                                          no-mixed-spaces-and-tabs
  328:25  error  'flowFile' is defined but never used                                                                                                                                           no-unused-vars
  328:35  error  'flowChunk' is defined but never used                                                                                                                                          no-unused-vars
  329:2   error  Mixed spaces and tabs                                                                                                                                                          no-mixed-spaces-and-tabs
  330:2   error  Mixed spaces and tabs                                                                                                                                                          no-mixed-spaces-and-tabs
  331:2   error  Mixed spaces and tabs                                                                                                                                                          no-mixed-spaces-and-tabs
  332:2   error  Mixed spaces and tabs                                                                                                                                                          no-mixed-spaces-and-tabs
  333:2   error  Mixed spaces and tabs                                                                                                                                                          no-mixed-spaces-and-tabs
  334:2   error  Mixed spaces and tabs                                                                                                                                                          no-mixed-spaces-and-tabs
  335:2   error  Mixed spaces and tabs                                                                                                                                                          no-mixed-spaces-and-tabs
  336:2   error  Mixed spaces and tabs                                                                                                                                                          no-mixed-spaces-and-tabs
  337:2   error  Mixed spaces and tabs                                                                                                                                                          no-mixed-spaces-and-tabs
  338:2   error  Mixed spaces and tabs                                                                                                                                                          no-mixed-spaces-and-tabs
  340:2   error  Mixed spaces and tabs                                                                                                                                                          no-mixed-spaces-and-tabs
  341:2   error  Mixed spaces and tabs                                                                                                                                                          no-mixed-spaces-and-tabs
  342:2   error  Mixed spaces and tabs                                                                                                                                                          no-mixed-spaces-and-tabs
  343:2   error  Mixed spaces and tabs                                                                                                                                                          no-mixed-spaces-and-tabs
  344:2   error  Mixed spaces and tabs                                                                                                                                                          no-mixed-spaces-and-tabs
  345:2   error  Mixed spaces and tabs                                                                                                                                                          no-mixed-spaces-and-tabs
  346:2   error  Mixed spaces and tabs                                                                                                                                                          no-mixed-spaces-and-tabs
  347:2   error  Mixed spaces and tabs                                                                                                                                                          no-mixed-spaces-and-tabs
  347:11  error  'OC' is not defined                                                                                                                                                            no-undef
  347:41  error  't' is not defined                                                                                                                                                             no-undef
  347:43  error  Strings must use doublequote                                                                                                                                                   quotes
  347:57  error  Strings must use doublequote                                                                                                                                                   quotes
  348:2   error  Mixed spaces and tabs                                                                                                                                                          no-mixed-spaces-and-tabs
  354:4   error  '$' is not defined                                                                                                                                                             no-undef
  369:4   error  '$' is not defined                                                                                                                                                             no-undef
  372:21  error  'response' is defined but never used                                                                                                                                           no-unused-vars
  401:59  error  'index' is defined but never used                                                                                                                                              no-unused-vars
  401:66  error  'arr' is defined but never used                                                                                                                                                no-unused-vars
  441:16  error  Strings must use doublequote                                                                                                                                                   quotes
  451:4   error  Unexpected console statement                                                                                                                                                   no-console
  452:4   error  Unexpected console statement                                                                                                                                                   no-console
  464:2   error  Mixed spaces and tabs                                                                                                                                                          no-mixed-spaces-and-tabs
  465:2   error  Mixed spaces and tabs                                                                                                                                                          no-mixed-spaces-and-tabs
  470:15  error  Unexpected side effect in "filteredFiles" computed property                                                                                                                    vue/no-side-effects-in-computed-properties
  471:7   error  Unexpected console statement                                                                                                                                                   no-console
  473:44  error  Missing semicolon                                                                                                                                                              semi
  475:17  error  Missing semicolon                                                                                                                                                              semi
  477:16  error  Missing semicolon                                                                                                                                                              semi
  478:15  error  Missing semicolon                                                                                                                                                              semi
  481:15  error  Unexpected side effect in "filteredFiles" computed property                                                                                                                    vue/no-side-effects-in-computed-properties
  482:29  error  Missing semicolon                                                                                                                                                              semi
  485:15  error  Unexpected side effect in "filteredFiles" computed property                                                                                                                    vue/no-side-effects-in-computed-properties
  486:41  error  Missing semicolon                                                                                                                                                              semi
  489:15  error  Unexpected side effect in "filteredFiles" computed property                                                                                                                    vue/no-side-effects-in-computed-properties
  490:45  error  Missing semicolon                                                                                                                                                              semi
  499:2   error  Mixed spaces and tabs                                                                                                                                                          no-mixed-spaces-and-tabs
  500:2   error  Mixed spaces and tabs                                                                                                                                                          no-mixed-spaces-and-tabs
  501:2   error  Mixed spaces and tabs                                                                                                                                                          no-mixed-spaces-and-tabs
  520:37  error  'vnode' is defined but never used                                                                                                                                              no-unused-vars
  533:5   error  '$' is not defined                                                                                                                                                             no-undef
  537:5   error  '$' is not defined                                                                                                                                                             no-undef
  538:6   error  '$' is not defined                                                                                                                                                             no-undef
  540:5   error  '$' is not defined                                                                                                                                                             no-undef
  541:6   error  '$' is not defined                                                                                                                                                             no-undef
  559:5   error  '$' is not defined                                                                                                                                                             no-undef
  563:5   error  '$' is not defined                                                                                                                                                             no-undef
  564:6   error  '$' is not defined                                                                                                                                                             no-undef
  566:5   error  '$' is not defined                                                                                                                                                             no-undef
  567:6   error  '$' is not defined                                                                                                                                                             no-undef
  572:28  error  'binding' is defined but never used                                                                                                                                            no-unused-vars
  572:37  error  'vnode' is defined but never used                                                                                                                                              no-unused-vars
  573:22  error  '$' is not defined                                                                                                                                                             no-undef
  575:6   error  '$' is not defined                                                                                                                                                             no-undef
  576:7   error  '$' is not defined                                                                                                                                                             no-undef
  579:6   error  '$' is not defined                                                                                                                                                             no-undef
  580:7   error  '$' is not defined                                                                                                                                                             no-undef

```

**Comment by TessyPowder** [comment]
I know, but webpack builds anyways. I will try to fix most of these errors.

**Comment by TessyPowder** [comment]
The errors are from eslint (not webpack)

**Comment by e-alfred** [comment]
The build process still doesn't work with `npm run build`:

```
cat .npm/_logs/2020-05-23T21_12_40_839Z-debug.log 
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build', '--dev' ]
2 info using npm@6.14.4
3 info using node@v12.16.3
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle flowupload@0.1.8~prebuild: flowupload@0.1.8
6 info lifecycle flowupload@0.1.8~build: flowupload@0.1.8
7 verbose lifecycle flowupload@0.1.8~build: unsafe-perm in lifecycle true
8 verbose lifecycle flowupload@0.1.8~build: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/var/www/html/apps/flowupload/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
9 verbose lifecycle flowupload@0.1.8~build: CWD: /var/www/html/apps/flowupload
10 silly lifecycle flowupload@0.1.8~build: Args: [
10 silly lifecycle   '-c',
10 silly lifecycle   'NODE_ENV=production webpack --progress --hide-modules --config webpack.prod.js'
10 silly lifecycle ]
11 silly lifecycle flowupload@0.1.8~build: Returned: code: 2  signal: null
12 info lifecycle flowupload@0.1.8~build: Failed to exec build script
13 verbose stack Error: flowupload@0.1.8 build: `NODE_ENV=production webpack --progress --hide-modules --config webpack.prod.js`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:310:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:310:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid flowupload@0.1.8
15 verbose cwd /var/www/html/apps/flowupload
16 verbose Linux 4.19.0-6-amd64
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build" "--dev"
18 verbose node v12.16.3
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 2
22 error flowupload@0.1.8 build: `NODE_ENV=production webpack --progress --hide-modules --config webpack.prod.js`
22 error Exit status 2
23 error Failed at the flowupload@0.1.8 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]

```

**Comment by TessyPowder** [comment]
I can build it, there are some warnings from eslint but building works. I will try to get rid of all the eslint errors. Wich npm version do you use ?

**Comment by TessyPowder** [comment]
or should we remove eslint completely ? I only added it because it was included in the nextcloud vue example

**Comment by e-alfred** [comment]
Currently these versions:

```
node v12.16.3
npm  v6.14.4
```

**Pull request merged**
