### PR TITLE
Uploadspeed detection

### PR DESCRIPTION
**Pull request by TessyPowder**
implements #44 

image

The per file speed is hidden on mobile devices (not enough space)

Tested on Nextcloud 16 , but should also work fine on 15 and 17

### CODE REVIEW

**Comment by TessyPowder** [comment]
Ready to merge, if you ask me

**Comment by e-alfred** [comment]
Do you think we should re-add the "time remaining" for each download if there is enough space to display them (like on desktops/tablets)?

**Comment by TessyPowder** [comment]
I'm not sure. I actually haven't tested Flowupoad on a Tablet.

The table width calculation on Desktop works differently than on mobile.
On Desktop the id, Size, progress and Uploadspeed column have a fixed width (in percent).
On Mobile the browser manages every column width.

I actually don't know how to hide columns in css the way I would like to:
If there's not enough space the progressbar should be hidden.
If that's not enough the uploadspeed should be hidden.
And if theres still not enough space the completed size should be hidden.

But i dont think thats even possible with pure CSS. It would probably need JS and CSS.
I will probably try if its possible with js but it might get a bit janky.

**Comment by TessyPowder** [comment]
This is how it  looks on a tablet
image

It does hide everything it hides on phones

**Comment by e-alfred** [comment]
I think it will be okay for now. Additional UI changes can be done in a later PR if needed.

**Pull request merged**
