### PR TITLE
Upload to multiple locations (new Attempt)

### PR DESCRIPTION
**Pull request by TessyPowder**
new attempt to implement [this PR](https://github.com/e-alfred/flowupload/pull/72)
Reusing some code from NastuzziSamy (not anymore because we moved no vue.js)
I am not forking this directly from NastuzziSamy because so much changed in flowupload master.

### CODE REVIEW

**Comment by TessyPowder** [comment]
Theres a lot to do because especially app.js and the different controllers aren't compatible to Flowupload master

**Comment by TessyPowder** [comment]
TODO:
- reorganise angular controllers
- integrating app.js from NastuzziSamy into this PR
- Database connection
- testing on Nextcloud 15
- testing on Nextcloud 16
- testing on Nextcloud 17

**Comment by TessyPowder** [comment]
I integrated everything from NastuzziSamy into the current version of flowupload.
But i think there are many improvements to do:

**I don't get why adding files and folders should be in the sidebar**. (Is it possible to implement them like they were before with multiple upload folders ?)

There are a few other UI changes i would like to make.

And another question is: Why are the locations saved server side ? Wouldn't it be enough to handle them client side ?

**Comment by e-alfred** [comment]
> I don't get why adding files and folders should be in the sidebar. (Is it possible to implement them like they were before with multiple upload folders ?)

I am not sure either, the UI design with the old PR is somewhat problematic anyway and we should use the official folder selection UI and other components to make it more coherent with the rest of Nextcloud anyway. Do you have a screenshot/list of changes to the UI you want to make? 

> Why are the locations saved server side ? Wouldn't it be enough to handle them client side ?

Probably yes, but it might be convenient for users to reuse locations used in the past.

**Comment by TessyPowder** [comment]
I changed the add location design:

# before:
image
clicked:
image


# now:
image
clicked:
image


Now its more in line with the nextcloud design (see [here](https://docs.nextcloud.com/server/16/developer_manual/design/navigation.html#new-button)

**Comment by TessyPowder** [comment]
> Do you have a screenshot/list of changes to the UI you want to make?

I will add them to the TODO List

**Comment by TessyPowder** [comment]
> the UI design with the old PR is somewhat problematic

I agree

**Comment by TessyPowder** [comment]
> Probably yes, but it might be convenient for users to reuse locations used in the past.

My Browser saves the previous paths as autofills , but we could implement account wide autofill reccomendations.
image

I personally wouldn't like having maybe unneccesary destinations in that list on every client.
Also server side would really mess up multiple instances of flowupload on the same account.

**Comment by TessyPowder** [comment]
> folder selection UI

What do you mean by that ?

This ?
image

or something different ?

**Comment by TessyPowder** [comment]
This is how it looks now:

image

**Comment by TessyPowder** [comment]
> This is how it looks now:
> 
> image

I had to completely replicate the behaviour of the two buttons because the ng-flow implementation isn't flexible enough. And now the buttons work.

**Comment by e-alfred** [comment]
Nice work! About the folder picker I thought about this one (used in the Collabora app):

image

**Comment by TessyPowder** [comment]
> About the folder picker I thought about this one (used in the Collabora app):

That looks really nice. So how should we do the UI ?

**Comment by TessyPowder** [comment]
Do we want to keep this ?
image
or completely use the Folder Picker dialog ?

**Comment by TessyPowder** [comment]
> Do we want to keep this ?
> image

If not:
How do we want to implement previous location recommendations ?

**Comment by e-alfred** [comment]
I think the folder selection UI is easier to use for users, otherwise they would have to figure out the path (which could get complicated if they have special characters/spaces in there or even a very long path) and enter it manually.

As a default we could still leave the /flowupload folder there as a default, so people can always upload there, otherwise they can select folders they would like to upload to by picking the folder using the folder picker.

**Comment by TessyPowder** [comment]
> As a default we could still leave the /flowupload folder there as a default, so people can always upload there
I plan to let the user choose permanent folders which are saved account wide and permanent folders that don't get saved on the server.
So a dB connection is still necessary.
Because I don't want to use location IDs there should be no bugs if 2 clients on the same user are marking locations as permanent/non permanent at the same time.

**Comment by TessyPowder** [comment]
I implemented the File picker and i removed this input box:
> image

**Comment by TessyPowder** [comment]
This is how it looks now:

image

**Comment by e-alfred** [comment]
I tested you branch and it works very well already. The UI is quite nice too now. Do you think it can be merged soon?

**Comment by TessyPowder** [comment]
There is still a lot to do (drag and drop , DB connection ...). 
I don't know how much time I will have in the next 2 weeks (I am still at school and there are a lot of tests soon 🙁) , so worst case it will take about 3 weeks to be ready to get merged.

**Comment by e-alfred** [comment]
No problem, it is done when it is done. :thumbsup:

**Comment by TessyPowder** [comment]
Drag and Drop is finished

**Comment by e-alfred** [comment]
I found a bug in with the drag and drop feature: If I drop a folder on it, it doesn't show all the files in the table, instead only the folder name is shown. Starting to upload fails because the folder cannot be found of course.

**Comment by TessyPowder** [comment]
> I found a bug in with the drag and drop feature: If I drop a folder on it, it doesn't show all the files in the table, instead only the folder name is shown. Starting to upload fails because the folder cannot be found of course.

I know. I am working on it. But do do it properly i have to change a few other things.
Also i am working on removing ng-flow completely, becuase it makes development harder that neccesary.

**Comment by e-alfred** [comment]
Also there is another problem with the selection of folders: Currently the app does not support external storage (as mentioned in this bug report: https://github.com/e-alfred/flowupload/issues/46) so we have a problem if a user selects a folder residing on external storage.

**Comment by e-alfred** [comment]
> Also i am working on removing ng-flow completely, becuase it makes development harder that neccesary.

Do you intend to use flow.js only for uploading or removing it altogether?

**Comment by TessyPowder** [comment]
> Do you intend to use flow.js only for uploading or removing it altogether?

flow.js only, without ng-flow

(because ng-flow is not necessary, it will improve lod time, it will make adding features easier, we can use the newest version of flow.js without having to move to angular 2 and as a preparation for #74 )

**Comment by TessyPowder** [comment]
> Also there is another problem with the selection of folders: Currently the app does not support external storage (as mentioned in this bug report: #46)

I fixed this issue

> removing ng-flow completely

done

> so we have a problem if a user selects a folder residing on external storage

I will test that soon

**Comment by TessyPowder** [comment]
We are now using the newest version of flow.js 🎉

**Comment by TessyPowder** [comment]
Starring frontend is done

**Comment by TessyPowder** [comment]
> so we have a problem if a user selects a folder residing on external storage

I guess the easiest way to fix that issue is to support External Storages. I will see if i can do that.
But for that i have to modify the flow backend. I don't know if this is a problem , because the Backend probably won't get updated to a newer version , but still ...

**Comment by TessyPowder** [comment]
> I guess the easiest way to fix that issue is to support External Storages

It was actually extremely easy (just 2 lines of code).
But i don't have a good way to test how good this works. I don't use external storages normally. And Dropbox and Google Drive external storages are not yet available for Nextcloud 17. 
So i tried it with a Nextcloud external storage pointing to a test user on my server. It worked fine with with small files but my server wasn't able to handle a 50 MB File (hopefully because my server is really slow (AMD Phenom™ II X4 810) and not because my solution doesn't work)

Can somebody here please test this ?

**Comment by e-alfred** [comment]
I tried your fix that allows uploads to external storage which does indeed create files, but they are zero bytes in size (currently SFTP, I will test other types as well). The table listing all the files in the Flowupload app shows an error after finishing uploading which is strange. It seems like the locking does not work:

`{"reqId":"a70W1J8K0n4EaEHZWfhr","level":3,"time":"2019-12-01T22:09:20+00:00","remoteAddr":"192.168.1.11","user":"admin","app":"index","method":"POST","url":"\/index.php\/apps\/flowupload\/ajax\/upload.php","message":{"Exception":"Flow\\FileLockException","Message":"failed to lock file: \/test alfred\/796638b5-ea4d-47bb-b48b-ebb6eb1cd2d9\/MOCCA Webstart (MOCCA) from mocca.jnlp.desktop","Code":0,"Trace":[{"file":"\/var\/www\/html\/apps\/flowupload\/ajax\/Flow\/Basic.php","line":47,"function":"save","class":"Flow\\File","type":"->","args":["\/test alfred\/796638b5-ea4d-47bb-b48b-ebb6eb1cd2d9\/MOCCA Webstart (MOCCA) from mocca.jnlp.desktop"]},{"file":"\/var\/www\/html\/apps\/flowupload\/ajax\/upload.php","line":59,"function":"save","class":"Flow\\Basic","type":"::","args":["\/test alfred\/796638b5-ea4d-47bb-b48b-ebb6eb1cd2d9\/MOCCA Webstart (MOCCA) from mocca.jnlp.desktop",{"__class__":"Flow\\Config"},{"__class__":"Flow\\Request"}]},{"file":"\/var\/www\/html\/lib\/private\/Route\/Route.php","line":155,"args":["\/var\/www\/html\/apps\/flowupload\/ajax\/upload.php"],"function":"require_once"},{"function":"OC\\Route\\{closure}","class":"OC\\Route\\Route","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"\/var\/www\/html\/lib\/private\/Route\/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"Closure"},{"_route":"flowupload_ajax_upload"}]},{"file":"\/var\/www\/html\/lib\/base.php","line":1000,"function":"match","class":"OC\\Route\\Router","type":"->","args":["\/apps\/flowupload\/ajax\/upload.php"]},{"file":"\/var\/www\/html\/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"\/var\/www\/html\/apps\/flowupload\/ajax\/Flow\/File.php","Line":165,"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:70.0) Gecko\/20100101 Firefox\/70.0","version":"17.0.1.1"}
`

I think for now only the official external storage types should be supported (Webdav, FTP, SFTP, SMB, S3, Openstack), other types are definitely nice to have, but probably too much hassle for now.

I will post a call for testing to the forum, I hope we can get more testers on board with that. What do you think?

**Comment by TessyPowder** [comment]
Ok. That error does make sense. Currently file locking is done via the Filesystem::fopen , but Nextcloud has its own file locking system. I will try to use the Nextcloud API for that tomorrow

**Comment by TessyPowder** [comment]
I tried upoading with all file locking code disabled. It did work with FTP.

_But not with a other user on the same Nextcloud instance , because something timed out and i think its just my server not being able to handle all those requests twice._

So i guess the only problem is the file locking. Everything else seems to work fine.

**Comment by TessyPowder** [comment]
I will now try to replace the previous file locking with the nextcloud api for file locking.

**Comment by TessyPowder** [comment]
> I will now try to replace the previous file locking with the nextcloud api for file locking.

Its a more complicated that i thought.

And is file locking even necessary?
The file will not appear in the user interface before all chunks are assembled anyways.
And all Nextcloud apps waiting for a file to get uploaded (for example [nextcloud antivirus](https://github.com/nextcloud/files_antivirus) wont not do anything until everything is done, because nextcloud gets informed that something changed after the chunks got assembled.

**So does file locking even make sense in this scenario ?**

**Comment by e-alfred** [comment]
The file gets copied to its final destination after it got uploaded to the flowupload_tmp directory, so locking shouldn't be a problem. 

But there is a problem if a user has no space allocated on the local filesystem and only uses external storage: The upload will most probably fail. So either the file is written immediately to the external storage and chunks are written there one by one (then we have to make sure file locking works) or the user somehow has to allocate enough storage for a temporary upload.

Aside from that we also need to support shared folders/group folders if we allow users to select folders in their folder hierarchy.

**Comment by TessyPowder** [comment]
> The file gets copied to its final destination after it got uploaded to the flowupload_tmp directory, so locking shouldn't be a problem.

Nice. I will just remove file locking.



> Aside from that we also need to support shared folders/group folders if we allow users to select folders in their folder hierarchy.

I will try this, but i think the nextcloud filesystem api handles that on it own.

> But there is a problem if a user has no space allocated on the local filesystem and only uses external storage

Seems like a very rare usecase ...

> the file is written immediately to the external storage and chunks are written there one by one

... , but i don't think writing chunks to the external storage is a good idea (performance !)

We could just let the admin choose the temp directory (relative to the users home folder)

**Comment by e-alfred** [comment]
Nextcloud 18 is already in beta, it should be on our radar for testing.

**Comment by TessyPowder** [comment]
> Nextcloud 18 is already in beta, it should be on our radar for testing.

I will add that to the todo list

**Comment by TessyPowder** [comment]
I am currently working on the Db part, but it might take a while, because i never worked with the Db APIs in Nextcloud before.

**Comment by e-alfred** [comment]
The recommended way to do database connections (from the Nextcloud devs) is using the Querybuilder: https://docs.nextcloud.com/server/18/developer_manual/app/storage/database.html?highlight=querybuilder

**Comment by TessyPowder** [comment]
Sorry for not replying for so long.
I was pretty busy, but i will have more time to work on this soon.
I know how to do Nextcloud DB stuff, but i don't like it very much (too much code for such a little fearure). 
I had started with the database programming a while ago, but i lost some of my progress due to a nextcloud update, wich replaced my development version with the newest from the store.
Anyways i now use a seperate nextcloud instance for development.

**Comment by bsommerhalder** [comment]
> 
> > But there is a problem if a user has no space allocated on the local filesystem and only uses external storage
> 
> Seems like a very rare usecase ...
> 

This might apply to my usecase. My NC instance is installed on a 30GB AWS SSD EBS volume, and my storage for data is an S3 bucket (set as primary storage). If a user wanted to upload say a 100GB file, there wouldn't be room in a temp directory on the 30GB installation directory for an entire 100GB file prior to being written to S3.

**Comment by TessyPowder** [comment]
> This might apply to my usecase. My NC instance is installed on a 30GB AWS SSD EBS volume, and my storage for data is an S3 bucket (set as primary storage). If a user wanted to upload say a 100GB file, there wouldn't be room in a temp directory on the 30GB installation directory for an entire 100GB file prior to being written to S3.

We could add a Option the admin can toggle, but i think we should discuss this in a seperate issue / Pull Request.

**Comment by TessyPowder** [comment]
I am now working on this again, but to implement the Network request to star / unstar a Location i will redo the Request Routing and use a Page Controller.

**Comment by TessyPowder** [comment]
**Quick Update:**
Development is going well, but i am not going to push my changes to github for a bit, because not everything works yet.
I completely redid the routing:
- I moved the Navigation Bar Link from app.php to info.xml (that's how it should be done in modern Nextcloud apps)
- I redid routes.php (like shown [here](https://docs.nextcloud.com/server/18/developer_manual/app/requests/routes.html#routing))
- I put everything into Services and Controllers in /lib rather than php files in /ajax/

The only thing that doesn't work yet is the integration of the Flow Libary (as a Service), but i am working on that.

I think the code will be much cleaner and easier to maintain when i am done.

**Comment by daleosm** [comment]
Hello, I found this from [here](https://github.com/e-alfred/flowupload/issues/46) as I'm also using S3 primary storage on my Nextcloud instance. I have also tried your zip in the mentioned thread and received the same problem as  bsommerhalder. Do you have a fix as of yet? 

I would be happy help in anyway as the native uploads in Nextcloud only provides 500kb/s whilst flowupload will upload at 1mb/s (My ISP upload limit) It's a strange quirk that I can't quite fathom.

**Comment by TessyPowder** [comment]
> Do you have a fix as of yet?

Not yet. I am ill since a few days and can't work on flowupload 😒

**Comment by TessyPowder** [comment]
I am still ill :(

**Comment by e-alfred** [comment]
@TessyPowder Hope you are getting better especially now. It would be great to move forward with this PR at some point.

**Comment by TessyPowder** [comment]
I am fine (i was ill for 2 weeks). Due to the corona virus, i have more freetime (no school), but i am currently working on another project. I will probably continue development on this in a week

**Comment by e-alfred** [comment]
For now I think we don't have to care much about Nextcloud 15 anymore but instead also prepare for Nextcloud 19 (master is already tested on the latest beta versions, works perfectly).

**Comment by e-alfred** [comment]
Master broke on the latest Nextcloud 19 Beta releases (one reason I don't publish releases for new Nextcloud versions prematurely anymore), it seems like we have to allow unsave-eval in our CSP (Flowjs and AngularJS use it heavily).

**Comment by e-alfred** [comment]
Master and this PR broke in recent betas and the RC of Nextcloud 19 hard (thats why I don't like to release apps early for new Nextcloud versions), I was able to fix the UI, but uploads still don't work for now:

```
diff --git a/appinfo/routes.php b/appinfo/routes.php
index df1b7be..de5ac74 100644
--- a/appinfo/routes.php
+++ b/appinfo/routes.php
@@ -1,7 +1,7 @@
 <?php
 
-$this->create('flowupload_index', '/')
+$this->create('flowupload_index', '/apps/flowupload')^M
        ->actionInclude('flowupload/index.php');
```

**Comment by TessyPowder** [comment]
I uploaded my currently not working development version [here](https://github.com/TessyPowder/flowupload/tree/multiple-locations-dev)

Because it uses much more Modern APIs for routing it might work better, but since i worked on it quite a while ago i don't remember how ready it is.

**Comment by TessyPowder** [comment]
routes.php is completely rewritten in my development version: https://github.com/TessyPowder/flowupload/commit/1c0d7d08618ad9a55453f0f2b232a2037b49b9f0#diff-0e033fd8797499a87a6bf2ffccef5c3c

I think it should be easier to get my dev version working on nextcloud 19

**Comment by TessyPowder** [comment]
> I uploaded my currently not working development version [here](https://github.com/TessyPowder/flowupload/tree/multiple-locations-dev)

I used a lot of code from: https://github.com/nextcloud/app-tutorial

I am not sure how much time i will have in the next weeks, but i will try to work on flowupload.

**Comment by TessyPowder** [comment]
I am installing a Nextcloud 19 Beta Docker for testing now. I will try to get my current development version to work.

**Comment by TessyPowder** [comment]
I think i get get the Database Stuff working in the next days.
So far no CSP errors in my development version.
Uploading isn't done yet, because the flow backend libary doesn't work yet.
When i working, i push a commit every hour or so to the multiple-locations-dev branch

**Comment by TessyPowder** [comment]
THE DATABASE CONNECTION WORKS. Completely.
The error that demotivated me a few weeks ago, was actually pretty small and easy to fix.

**Comment by TessyPowder** [comment]
I think we can get this Merge Request stable until nextcloud 19 is released (the frontend code is still a bit messy, unstarring isn't done yet and uploading isn't done yet but its going well so far)

**Comment by TessyPowder** [comment]
The Flow Libary works now, but uploading doesn't work quite yet. It doesn't throw any errors, so i will debug it tomorrow

**Comment by TessyPowder** [comment]
> The Flow Libary works now, but uploading doesn't work quite yet. It doesn't throw any errors, so i will debug it tomorrow

What i found out so far:
- the upload request gets routed properly
- the flow libary seems to work
- no file data seems to be send (i don't know why. Could be a frontend error or some security thing)
- nothing gets stored (not even chunks in the cache

I don't know why it doesn't work yet

**Comment by TessyPowder** [comment]
I don't know why it is not working. I tried debugging everything and the result is: the files don't even get send and therefore not processed
SO i tried to find out if this is nextcloud 19 related and i installed it on my normal nextcloud server and it didn't work there either. Now i installed the master of flowupload again and it doesn't work anymore. That's so confusing.
 I tried debugging the dev version for the last 5 hours and didn't find a reason why it shouldn't work.
The POST requests are never done. It always just checks if chunks have been uploaded (via GET)

**Comment by TessyPowder** [comment]
I could fix my problems with master by reinstalling it. It was just a cache problem.

**Comment by TessyPowder** [comment]
I found the error:

Status Codes can't get set with header(), because the nextcloud App Framework needs a HttpReturn Object as Return, where you can set the status code.
The Frontend Flow.js Libary breaks when the response on the request, that finds out if some chunk is already done isn't empty. So i wrote a custom http return Object.
Uploading works now, but there are many things i need to clean up.

**Comment by TessyPowder** [comment]
I cleaned the uploading backend up and merged everything in this branch/merge request.

I am now going to focus on cleaning up the frontend, but probably with vue.js and not angular. We plan to move to Vue.js (#74 ) anyways so why do the work twice :)

**Comment by TessyPowder** [comment]
I started the migration to vue.js, but we have to decide if we want to use webpack. With webpack we could use the [nextcloud vue](https://github.com/nextcloud/nextcloud-vue) "Libary", wich could be extremely useful. But webpack would need to be implemented in all our workflows (release, codacity and development).
What do you think @e-alfred Should we use webpack ?

**Comment by TessyPowder** [comment]
I started the migration to webpack in [this branch](https://github.com/TessyPowder/flowupload/tree/multiple-locations-webpack).
So far it's going great an if everything goes well its done tomorrow

**Comment by e-alfred** [comment]
Pretty awesome work! Migrating to Vue and Webpack would be indeed a good option to get the app onto a more modern base, ditching AngularJS has to be done after all until at least next year, so this is a very good move. We should just make it well maintainable for the future so we can keep the app running for a long time. Also having a dev/production environment managed using Webpack could help development for new releases and using something like Dependabot to keep all of our dependencies current.

**Comment by TessyPowder** [comment]
The UI is stable now, but uploading doesn't quite work yet. The Pick a file Popup and Drag and Drop work, but the files don't get added to the queue for some reason

**Comment by TessyPowder** [comment]
The behavior is really weird. The files get added to flow.js correctly but aborted after a few milliseconds. Vue.js seems to be messing with the array. Maybe the flow.js libary is setting data in a way that can't be detected by vue.js. If i don't add the flow object to the location array in the vue intance files don't disappear. I really hope this can be fixed somehow. If flow.js was completely incompatible with vue.js that would be really bad. I am going to further debug this problem

**Comment by TessyPowder** [comment]
EDIT: It's not Vue.js. If i comment the files table the files don't get aborted.

**Comment by TessyPowder** [comment]
> but the files don't get added to the queue for some reason

That was a very dumb reason:
I wrote v-click instead of v-on:click and that aborted file right after it was loaded into the Files Table.
I just replaced ng-click with v-click without thinking, but in vue js it is called v-on:click of course.

Uploading works now, with both drag and Drop and the File/Folder Picker 😃

**Comment by TessyPowder** [comment]
Everything works now. I fixed the last errors in the UI.
There's only one thing left to do: Block starring the same location twice, but then this PR can be merged :)
There are still some errors from eslint to clean up (mostly mixed tabs and spaces).
I will merge everything into the branch of this PR and i hope we can merge this into master soon.

@e-alfred If you want to help you could test if there some bugs left (especially wether the databases get installed correctly when installing the app)

**Comment by e-alfred** [comment]
Awesome work! I will test it and ask on the Nextcloud forum if somebody wants to help test it out too: 

https://help.nextcloud.com/t/call-for-testing-flowupload-1-0/81557

Do you have some build instructions for Webpack? Maybe a simple package would be great for any testers out there.

If you don't mind I would like to bump the version number to Flowupload 1.0 as soon as this is finished because the app is now mature enough I think.

**Comment by TessyPowder** [comment]
> If you don't mind I would like to bump the version number to Flowupload 1.0 as soon as this is finished because the app is now mature enough I think.

Sounds like a great idea

**Comment by TessyPowder** [comment]
> Do you have some build instructions for Webpack? Maybe a simple package would be great for any testers out there that could be uploaded to the Nextcloud App Store as a Nightly.

Cool. Heres a build of the branch: 
[flowupload.zip](https://github.com/e-alfred/flowupload/files/4629419/flowupload.zip)

**Comment by TessyPowder** [comment]
It can be built for production with: "npm run build"
/node_modules/ and /src/ should not be included in production.

**Comment by TessyPowder** [comment]
If nobody finds any bugs, we can merge this soon.
I don't plan to add any features to this pull request (but in others 😃 )

**Comment by e-alfred** [comment]
> It can be built for production with: "npm run build" /node_modules/ and /src/ should not be included in production.

This should probably go into the .ci/release_app.sh script and the Readme.

**Comment by e-alfred** [comment]
I tested you zipped version, it works pretty well. UI wise, do we need the settings menu in the bottom left corner at the moment? It is pretty empty. Maybe this feature could be set there in the future: https://github.com/e-alfred/flowupload/issues/75

**Comment by e-alfred** [comment]
Seems like I was a bit too fast assuming everything works. I tried to upload to an external storage and it immediately shows "error" after finishing the upload. The file is never created in the folder either showing these messages:

```
$ is deprecated: The global jQuery is deprecated. It will be updated to v2.4 in Nextcloud 20 and v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 2 globals.js:61:15
Object { flowObj: Getter & Setter, bytes: Getter & Setter, file: Getter & Setter, name: Getter & Setter, size: Getter & Setter, relativePath: Getter & Setter, uniqueIdentifier: Getter & Setter, chunkSize: Getter & Setter, chunks: Getter & Setter, paused: Getter & Setter, … }
App.vue:465
[Vue warn]: Duplicate keys detected: 'false'. This may cause an update error.

found in

---> <App> at src/App.vue
       <Root> vue.runtime.esm.js:619
[Vue warn]: Duplicate keys detected: 'false'. This may cause an update error.

found in

---> <App> at src/App.vue
       <Root> 2 vue.runtime.esm.js:619
```

**Comment by TessyPowder** [comment]
> Seems like I was a bit too fast assuming everything works. I tried to upload to an external storage and it immediately shows "error" after finishing the upload. The file is never created in the folder either showing these messages:

Well i kind of knew that. Many external storages don't implement the functions we need to assemble the chunks. We need  a fallback method for assembling the chunks, but that will not be easy. I will try it in the next few days, but i can't guarantee that it will work with every External Storage.

**Comment by TessyPowder** [comment]
> I tested you zipped version, it works pretty well. UI wise, do we need the settings menu in the bottom left corner at the moment? It is pretty empty. Maybe this feature could be set there in the future: #75

#75 is exactly the reason why it's there, but we can comment it out for the release.

**Comment by e-alfred** [comment]
> Many external storages don't implement the functions we need to assemble the chunks.

Well, if that is the case, then maybe whitelisting might be an option. Do you know which ones work? I tested it with SFTP which seems not to work correctly at the moment.

**Comment by TessyPowder** [comment]
> Well, if that is the case, then maybe whitelisting might be an option. Do you know which ones work? I tested it with SFTP which seems not to work correctly at the moment.

Everyone that implements the fopen function should work. But that's not many so we need to find another way of assembling the chunks, if fopen isn't implemented. fopen is very efficient so we should use it whenever we can

**Comment by e-alfred** [comment]
> Everyone that implements the fopen function should work.

We should at least put a warning somewhere for now, otherwise people will open issues again about this even if we know that not all external storage types will work at the moment. Whitelisting would still be a better idea to limit functionality to working storage types.

**Comment by e-alfred** [comment]
Do you think we can merge it already? The PR still has the "draft" status.

**Comment by TessyPowder** [comment]
I updated the README to make it very clear that External Storages may not work yet.
I think we can merge this very soon. I will briefly go over the source code to see if i can see anything that still needs to be done.
I didn't test this PR on Nextcloud 16 and 17 but i am sure it will work. I don't think we use any new APIs that could break this app on old Nextcloud Versions.

**Comment by TessyPowder** [comment]
I added Strings to the Project that will need to be translated, but Transifex will take care of that. We don't have to exclude /js/ with l10nignore because no webpack built code will be in the repository (only in releases).

**Comment by TessyPowder** [comment]
I didn't spot any problems in the code. Are we ready to merge ?

**Comment by TessyPowder** [comment]
Codacity doesn't like my code (mostly because mixed " and '. And some of these warnings are totally useless) but i will clean that up later. Our priority right now should be supporting Nextcloud 19, wich will be released very soon.

**Comment by e-alfred** [comment]
I am not sure if Codacy is that useful for this project at all, but in the future Dependabot is useful probably for keeping our dependencies current. 

We could make a release for Nextcloud 19 and 18 only for now so older releases can still use the older legacy version of Flowupload that works still on those Nextcloud releases. Translations will be done by the awesome translators at Transiflex so they should be pushed here within a few days, if some strings are left that could be solved by a 

The only thing left is the release script in the .ci folder, I am not sure if it is needed anymore.

**Comment by TessyPowder** [comment]
> The only thing left is the release script in the .ci folder, I am not sure if it is needed anymore.

You could do the release manually or we have to update the script to run webpack before the release

**Comment by e-alfred** [comment]
Its done! I also enabled Dependabot because we already have a security vulnerability in our dependencies (minimist).

**Comment by e-alfred** [comment]
Flowupload 1.0 release is done: https://apps.nextcloud.com/apps/flowupload

**Pull request merged**
