### PR TITLE
Feature to hide all finished uploads

### PR DESCRIPTION
**Pull request by TessyPowder**
I personally often use flowupload to upload thousands of small files and i think its really annoying to scroll far down to see wich files are currently being uploaded.
In combination with the Sorting feature its now possible to always see the files , that are currently being uploaded, on the top of the page (sort by greatest progress).
On uploads with many files this can possibly also improve performance because there are less HTML elements.

image

### CODE REVIEW

**Comment by TessyPowder** [comment]
tested on Brave, Chrome, Firefox

**Comment by TessyPowder** [comment]
The text inside the button is a bit higher than the checkbox but i am not quite sure how to fix this.

**Comment by e-alfred** [comment]
Thanks for your help @TessyPowder! Are you interested in becoming a contributor to this project?

**Comment by TessyPowder** [comment]
> Thanks for your help @TessyPowder! Are you interested in becoming a contributor to this project?

Sure. Thanks 🙂

**Comment by TessyPowder** [comment]
> The text inside the button is a bit higher than the checkbox but i am not quite sure how to fix this.

Fix was really easy. I just didn't see that it worked last time i tried.

**Comment by TessyPowder** [comment]
I think this PR is now ready to merge 👍

**Pull request merged**
